[platformio]
default_envs = master, follower

[env]
platform = platformio/espressif32@6.10.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_flags =
  --no-stub
lib_ldf_mode = chain+
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -I src/common
  -D CAMERA_MODEL_XIAO_ESP32S3
  -D CORE_DEBUG_LEVEL=3

[env:master]
build_src_filter =
  +<common/>
  +<master/>
  -<follower/>
lib_deps =
  https://github.com/eclipse-zenoh/zenoh-pico.git#1.9.0
build_flags =
  ${env.build_flags}
  -D KIWI_MASTER

[env:follower]
build_src_filter =
  +<common/>
  +<follower/>
  -<master/>
lib_deps =
  sparkfun/SparkFun BNO08x Cortex Based IMU@1.0.6
build_flags =
  ${env.build_flags}
  -D KIWI_FOLLOWER

[env:follower_motor_ramp]
build_src_filter =
  +<motor_ramp_test/>
  -<common/>
  -<master/>
  -<follower/>
build_flags =
  ${env.build_flags}
  -D KIWI_FOLLOWER_MOTOR_RAMP_TEST

[env:follower_motor_encoder_map]
build_src_filter =
  +<motor_encoder_map/>
  -<common/>
  -<master/>
  -<follower/>
  -<motor_ramp_test/>
  -<dominion_boot_cal/>
build_flags =
  ${env.build_flags}
  -D KIWI_FOLLOWER_MOTOR_ENCODER_MAP

[env:follower_dominion_boot_cal]
build_src_filter =
  +<dominion_boot_cal/>
  -<common/>
  -<master/>
  -<follower/>
  -<motor_ramp_test/>
build_flags =
  ${env.build_flags}
  -D KIWI_FOLLOWER_DOMINION_BOOT_CAL
